// export const team = {
//   founders: [],
//   advisors: [],
//   conveners: [],
//   heads: [
//     {
//       Timestamp: "2024/03/03 12:27:50 pm GMT+5:30",
//       Username: "yashhirani26@gmail.com",
//       Name: "Yash Hirani",
//       "Position/ Role in Triveni": "Marketing head",
//       Department: "EC",
//       Semester: 6,
//       "Enrollment no": 210280111120,
//       "Phone Number": 9898535081,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/bzkmddhdfrne4a2s7mjh",
//     },
//     {
//       Timestamp: "2024/03/03 12:28:50 pm GMT+5:30",
//       Username: "mrshyora384@gmail.com",
//       Name: "Shyora Sahil",
//       "Position/ Role in Triveni": "Head of creative team",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113052,
//       "Phone Number": 9099426824,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/p64spffibl62z1cokxpc",
//     },
//     {
//       Timestamp: "2024/03/03 12:35:33 pm GMT+5:30",
//       Username: "shilpakaninwal@gmail.com",
//       Name: "Shilpa",
//       "Position/ Role in Triveni": "Creative team head",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113006,
//       "Phone Number": 7600218226,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/p2u7ynyijcfmnm7pbe8e",
//     },
//     {
//       Timestamp: "2024/03/03 2:12:51 pm GMT+5:30",
//       Username: "prajapatidhruv2000@gmail.com",
//       Name: "Dhruv Prajapati",
//       "Position/ Role in Triveni": "Events Head",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113039,
//       "Phone Number": 7043341434,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/upavqvmeru94wnk8axxk",
//     },
//     {
//       Timestamp: "2024/03/03 2:18:17 pm GMT+5:30",
//       Username: "ahaanthakore@gmail.com",
//       Name: "Ahaan Thakore",
//       "Position/ Role in Triveni": "Campaign Head",
//       Department: "Environment",
//       Semester: 4,
//       "Enrollment no": 220280113003,
//       "Phone Number": 8141265766,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/umqis45hp6x9n7s2eehh",
//     },
//     {
//       Timestamp: "2024/03/03 2:22:51 pm GMT+5:30",
//       Username: "slowluss@gmail.com",
//       Name: "Krushit Modi",
//       "Position/ Role in Triveni": "Campaign head",
//       Department: "Environment",
//       Semester: 4,
//       "Enrollment no": 220280113029,
//       "Phone Number": 7359375985,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/zemzenyj9a0vv1wfuesk",
//     },
//     {
//       Timestamp: "2024/03/03 2:43:02 pm GMT+5:30",
//       Username: "rutvi17patel@gmail.com",
//       Name: "Rutvi Moliya",
//       "Position/ Role in Triveni": "Marketing head",
//       Department: "Environment",
//       Semester: 4,
//       "Enrollment no": 220280113030,
//       "Phone Number": 9316370146,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/oddnega81yngc1htbdpe",
//     },
//     {
//       Timestamp: "2024/03/04 10:35:23 am GMT+5:30",
//       Username: "hppadhiyar14@gmail.com",
//       Name: "Hitika Padhiyar",
//       "Position/ Role in Triveni": "Event head",
//       Department: "Mechanical",
//       Semester: 6,
//       "Enrollment no": 210280119005,
//       "Phone Number": 7041812298,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/eiclmf9mqlzg3xihjdji",
//     },
//     {
//       Timestamp: "2024/03/04 1:30:48 pm GMT+5:30",
//       Username: "aangandave@gmail.com",
//       Name: "Aangan dave",
//       "Position/ Role in Triveni": "Campaigning head",
//       Department: "Ic",
//       Semester: 4,
//       "Enrollment no": 220280117001,
//       "Phone Number": 7990566548,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/hne8usnnujnddtbovy7w",
//     },
//     {
//       Timestamp: "2024/03/04 3:05:17 pm GMT+5:30",
//       Username: "dhruvil1808@gmail.com",
//       Name: "Dhruvil Moradiya",
//       "Position/ Role in Triveni": "Head of Web Development",
//       Department: "EC",
//       Semester: 4,
//       "Enrollment no": 22028011063,
//       "Phone Number": 7990740133,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ie1zs7e3rvp3s7blbise",
//     },
//     {
//       Timestamp: "2024/03/04 3:27:19 pm GMT+5:30",
//       Username: "akhilsudev.philomax@gmail.com",
//       Name: "Akhil Sudev",
//       "Position/ Role in Triveni": "Events Head",
//       Department: "Textile",
//       Semester: 6,
//       "Enrollment no": 220283129001,
//       "Phone Number": 9429899611,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/pczk7tr8uzleyxfsfefn",
//     },
//     {
//       Timestamp: "2024/03/04 7:14:18 pm GMT+5:30",
//       Username: "naitikmonapara@gmail.com",
//       Name: "Monapara naitik kishorbhai",
//       "Position/ Role in Triveni": "Core team head",
//       Department: "Biomedical",
//       Semester: 6,
//       "Enrollment no": 210280103024,
//       "Phone Number": 9978387756,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/pugv5zpsanwopsosl109",
//     },
//     {
//       Timestamp: "2024/03/04 8:38:54 pm GMT+5:30",
//       Username: "krunalswaghela@gmail.com",
//       Name: "Waghela Krunal Shantilal",
//       "Position/ Role in Triveni": "Event Head",
//       Department: "Automobile",
//       Semester: 6,
//       "Enrollment no": 210280102018,
//       "Phone Number": 7383316379,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/mjfi9v2hoocqkvrpvaqj",
//     },
//     {
//       Timestamp: "2024/03/06 12:09:44 pm GMT+5:30",
//       Username: "namanraw123@gmail.com",
//       Name: "Naman Joshi",
//       "Position/ Role in Triveni": "Sponsorship Head",
//       Department: "Electrical Engineering",
//       Semester: 6,
//       "Enrollment no": 210280109045,
//       "Phone Number": 9427066370,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/dwtygw9vvculdvicftv7",
//     },
//   ],
//   core: [],
//   members: [
//     {
//       Timestamp: "2024/03/03 2:15:18 pm GMT+5:30",
//       Username: "mahip5501@gmail.com",
//       Name: "Prajapati mahi",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113011,
//       "Phone Number": 9313387959,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/hr1qx1icz57phwfvjc5i",
//     },
//     {
//       Timestamp: "2024/03/03 2:15:48 pm GMT+5:30",
//       Username: "vanshikamodi73@gmail.com",
//       Name: "Vanshika modi",
//       "Position/ Role in Triveni": "Decoration committee",
//       Department: "Textile",
//       Semester: 6,
//       "Enrollment no": 220283129024,
//       "Phone Number": 9408477747,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/cvvoyvp7rhm6xtdlrwmo",
//     },
//     {
//       Timestamp: "2024/03/03 2:17:05 pm GMT+5:30",
//       Username: "zinzalaankush@gmail.com",
//       Name: "Ankush Zinzala",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Automobile",
//       Semester: 2,
//       "Enrollment no": 230280102141,
//       "Phone Number": 9714248176,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/spcozli7ded7rzc5stxh",
//     },

//     {
//       Timestamp: "2024/03/03 2:19:48 pm GMT+5:30",
//       Username: "hardipriyadarshi@gmail.com",
//       Name: "Hardi Priyadarshi",
//       "Position/ Role in Triveni": "Creative team",
//       Department: "Environment",
//       Semester: 2,
//       "Enrollment no": 230280113050,
//       "Phone Number": 9687242895,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/vk88q8njuudnleg7yfhg",
//     },
//     {
//       Timestamp: "2024/03/03 2:21:01 pm GMT+5:30",
//       Username: "krishsuthar1911@gmail.com",
//       Name: "Suthar Krish",
//       "Position/ Role in Triveni": "Creative Team member",
//       Department: "IC",
//       Semester: 2,
//       "Enrollment no": 230280117103,
//       "Phone Number": 9313843173,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/r84ult9juu2wgoov9ptd",
//     },

//     {
//       Timestamp: "2024/03/03 2:23:52 pm GMT+5:30",
//       Username: "dhyan0711@gmail.com",
//       Name: "Dhyan Patel",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Instrumentation and Control",
//       Semester: 2,
//       "Enrollment no": 230280117021,
//       "Phone Number": 9023184128,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/qedlx6h8ed1fwlt5hs2y",
//     },
//     {
//       Timestamp: "2024/03/03 2:24:11 pm GMT+5:30",
//       Username: "ishay5439@gmail.com",
//       Name: "Isha yadav",
//       "Position/ Role in Triveni": "Decoration team",
//       Department: "Textile",
//       Semester: 6,
//       "Enrollment no": 210280129011,
//       "Phone Number": 6355578848,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/s6bmtff43guckuqkwdar",
//     },
//     {
//       Timestamp: "2024/03/03 2:29:47 pm GMT+5:30",
//       Username: "aasthaumadhariya@gmail.com",
//       Name: "Aastha Umadhariya",
//       "Position/ Role in Triveni": "Marketing team member",
//       Department: "Environment",
//       Semester: 4,
//       "Enrollment no": 220280113054,
//       "Phone Number": 6354622720,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ruv8e0fsigjtcdurmaa4",
//     },
//     {
//       Timestamp: "2024/03/03 2:32:00 pm GMT+5:30",
//       Username: "gondaliyavilas635@gmail.com",
//       Name: "Arvi Gondaliya",
//       "Position/ Role in Triveni": "Creative team in triveni",
//       Department: "Instrumation and control",
//       Semester: 2,
//       "Enrollment no": 230280117003,
//       "Phone Number": 6352703745,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/zxkpwabheo8tlv5m3ppm",
//     },

//     {
//       Timestamp: "2024/03/03 2:46:42 pm GMT+5:30",
//       Username: "ruchigandhi1185@gmail.com",
//       Name: "Ruchi Gandhi",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Environment",
//       Semester: 2,
//       "Enrollment no": 230280113055,
//       "Phone Number": 9429867363,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ubjwm2o8qgtck9x2m8rd",
//     },
//     {
//       Timestamp: "2024/03/03 2:50:14 pm GMT+5:30",
//       Username: "rathodalpa585@gmail.com",
//       Name: "Alpa rathod",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Environment engineering",
//       Semester: 6,
//       "Enrollment no": 210280113031,
//       "Phone Number": 7069198582,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/jfbd1vai06u4hyy7thm2",
//     },
//     {
//       Timestamp: "2024/03/03 2:51:00 pm GMT+5:30",
//       Username: "hitishakavar1511@gmail.com",
//       Name: "Hitisha kavar",
//       "Position/ Role in Triveni": "member of creative team",
//       Department: "environment",
//       Semester: 6,
//       "Enrollment no": 210280113029,
//       "Phone Number": 95123914232,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/blf9tqaiwpcprut7jeia",
//     },
//     {
//       Timestamp: "2024/03/03 2:54:14 pm GMT+5:30",
//       Username: "panchalpratham1008@gmail.com",
//       Name: "panchal pratham",
//       "Position/ Role in Triveni": "creative work",
//       Department: "instrumentation and controls",
//       Semester: 2,
//       "Enrollment no": 230280117051,
//       "Phone Number": 8487820364,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ybukcwdxv9x9ve15zyjk",
//     },
//     {
//       Timestamp: "2024/03/03 3:44:56 pm GMT+5:30",
//       Username: "vidhanparmar089@gmail.com",
//       Name: "Vidhan Parmar",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Civil",
//       Semester: 6,
//       "Enrollment no": 210280106035,
//       "Phone Number": 8401441999,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/cux2zupizzxluucmviyg",
//     },
//     {
//       Timestamp: "2024/03/03 4:21:33 pm GMT+5:30",
//       Username: "diyutiwari2715@gmail.com",
//       Name: "Divyani Tiwari",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "I.C",
//       Semester: 2,
//       "Enrollment no": 230280117107,
//       "Phone Number": 8734972173,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/d1icwyxhyggq3jvgtzwk",
//     },
//     {
//       Timestamp: "2024/03/03 4:22:40 pm GMT+5:30",
//       Username: "shahprutha0609@gmail.com",
//       Name: "Shah prutha",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "IC",
//       Semester: 2,
//       "Enrollment no": 230280117093,
//       "Phone Number": 6354070583,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/f1ykeewz0r9cr8qbyw5f",
//     },
//     {
//       Timestamp: "2024/03/03 4:34:00 pm GMT+5:30",
//       Username: "khushi7321singh@gmail.com",
//       Name: "Singh Khushi narendra pratap",
//       "Position/ Role in Triveni": "Member of creative team",
//       Department: "Environmental engineering",
//       Semester: 6,
//       "Enrollment no": 210280113050,
//       "Phone Number": 9586250738,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/eknhoybz2ub44mkboz9v",
//     },
//     {
//       Timestamp: "2024/03/03 4:44:29 pm GMT+5:30",
//       Username: "07sambhav@gmail.com",
//       Name: "Sambhav Shah",
//       "Position/ Role in Triveni": "Creative Team Member",
//       Department: "Instrumentation and Control (I.C)",
//       Semester: 2,
//       "Enrollment no": 230280117090,
//       "Phone Number": 7359362681,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ohg4wymoa1vmvcahvxti",
//     },
//     {
//       Timestamp: "2024/03/03 4:46:46 pm GMT+5:30",
//       Username: "sarthakgore02@gmail.com",
//       Name: "Sarthak Gore",
//       "Position/ Role in Triveni": "Campaigning Team Member",
//       Department: "I.C.",
//       Semester: 2,
//       "Enrollment no": 230280117092,
//       "Phone Number": 9016474749,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/u3s6gqbyq63rn9vrxe16",
//     },
//     {
//       Timestamp: "2024/03/03 4:52:43 pm GMT+5:30",
//       Username: "patelkena74@gmail.com",
//       Name: "Kena patel",
//       "Position/ Role in Triveni": "Creative team of triveni",
//       Department: "Ic",
//       Semester: 2,
//       "Enrollment no": 230280117063,
//       "Phone Number": 9978886155,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ddwraiu63dv5cwkxvuby",
//     },
//     {
//       Timestamp: "2024/03/03 5:16:29 pm GMT+5:30",
//       Username: "kavyapatel3805@gmail.com",
//       Name: "Kavya patel",
//       "Position/ Role in Triveni": "Creative team",
//       Department: "IC",
//       Semester: 2,
//       "Enrollment no": 230280117031,
//       "Phone Number": 9265374989,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/lotezmf65ih9lrdavz6j",
//     },
//     {
//       Timestamp: "2024/03/03 5:21:35 pm GMT+5:30",
//       Username: "poojaroshiya11@gmail.com",
//       Name: "Pooja roshiya",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "I&C",
//       Semester: 2,
//       "Enrollment no": 230280117086,
//       "Phone Number": 6356720073,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/u8yhnahupbmlrlsg6wdu",
//     },
//     {
//       Timestamp: "2024/03/03 5:24:53 pm GMT+5:30",
//       Username: "kansagraumang91@gmail.com",
//       Name: "Kansagra umang",
//       "Position/ Role in Triveni": "Creative team members",
//       Department: "Ic",
//       Semester: 2,
//       "Enrollment no": 230280117029,
//       "Phone Number": 7048642441,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/yinzf0kzea9plobaamm6",
//     },
//     {
//       Timestamp: "2024/03/03 5:27:37 pm GMT+5:30",
//       Username: "vaidehicpatel31@gmail.com",
//       Name: "Patel Vaidehi Chetankumar",
//       "Position/ Role in Triveni": "Creative Team Member",
//       Department: "Environment Engineering",
//       Semester: 2,
//       "Enrollment no": 230280113043,
//       "Phone Number": 9313391455,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/lqy5qvcygnyq7atmtnyl",
//     },
//     {
//       Timestamp: "2024/03/03 5:37:14 pm GMT+5:30",
//       Username: "poojarathod2398@gmail.com",
//       Name: "Karan Rathod",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Mechanical",
//       Semester: 2,
//       "Enrollment no": 230280119110,
//       "Phone Number": 6356497758,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/btjrsciu0kw51c6rcead",
//     },
//     {
//       Timestamp: "2024/03/03 5:44:41 pm GMT+5:30",
//       Username: "shreyaaaaaamish070905@gmail.com",
//       Name: "Shreya Mishra",
//       "Position/ Role in Triveni": "Creative member",
//       Department: "Environment",
//       Semester: 2,
//       "Enrollment no": 230280113063,
//       "Phone Number": 8320725508,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/qvawt1fjwzaq0zlfatu0",
//     },
//     {
//       Timestamp: "2024/03/03 6:04:06 pm GMT+5:30",
//       Username: "roshnipatara767@gmail.com",
//       Name: "Roshni Patara",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Textile",
//       Semester: 6,
//       "Enrollment no": 220283129030,
//       "Phone Number": 7285076097,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/vnxw1p7umbrq4f8r6t8x",
//     },
//     {
//       Timestamp: "2024/03/03 6:08:22 pm GMT+5:30",
//       Username: "smitpatel5434@gmail.com",
//       Name: "Smit patel",
//       "Position/ Role in Triveni": "Creative team",
//       Department: "Instrumentation and control",
//       Semester: 2,
//       "Enrollment no": 230280117068,
//       "Phone Number": 7874164507,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/jol9zeb3aqdvsnnqcde7",
//     },
//     {
//       Timestamp: "2024/03/03 6:13:23 pm GMT+5:30",
//       Username: "sangharyasmin786@gmail.com",
//       Name: "Yasmin sanghar",
//       "Position/ Role in Triveni": "Decoration",
//       Department: "Ic",
//       Semester: 2,
//       "Enrollment no": 230280117091,
//       "Phone Number": 6351368735,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ko6fxejk1jhuilkjqfrc",
//     },
//     {
//       Timestamp: "2024/03/03 6:47:30 pm GMT+5:30",
//       Username: "bnhadiya53@gmail.com",
//       Name: "Bhargav",
//       "Position/ Role in Triveni": "Creative team",
//       Department: "Rubber technology",
//       Semester: 6,
//       "Enrollment no": 210280126008,
//       "Phone Number": 6359768714,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ifi7fgvbgiq3nrp45i91",
//     },
//     {
//       Timestamp: "2024/03/03 7:09:11 pm GMT+5:30",
//       Username: "ami2812004@gmail.com",
//       Name: "Amit rathod",
//       "Position/ Role in Triveni": "Creative team member",
//       Department: "Mechanical",
//       Semester: 6,
//       "Enrollment no": 210280119012,
//       "Phone Number": 9327082672,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/lglsuokjmswpak5azk66",
//     },
//     {
//       Timestamp: "2024/03/03 7:12:39 pm GMT+5:30",
//       Username: "trushilshyora18@gmail.com",
//       Name: "Trushil Ahir",
//       "Position/ Role in Triveni": "Creative Team Member",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113038,
//       "Phone Number": 9824994014,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/nch7eyr8sc2y3hjkect1",
//     },
//     {
//       Timestamp: "2024/03/03 7:24:11 pm GMT+5:30",
//       Username: "samarthpatel232232@gmail.com",
//       Name: "Samarth Vachhani",
//       "Position/ Role in Triveni": "Creative Team",
//       Department: "Environmental engineering",
//       Semester: 6,
//       "Enrollment no": 220284113015,
//       "Phone Number": 8866621021,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/rltdfbumri7ekthpzc6z",
//     },
//     {
//       Timestamp: "2024/03/03 7:49:46 pm GMT+5:30",
//       Username: "raj8483goswami@gmail.com",
//       Name: "Tanushka Goswami",
//       "Position/ Role in Triveni": "Creative Team Member",
//       Department: "Textile Technology",
//       Semester: 6,
//       "Enrollment no": 220283129045,
//       "Phone Number": 9316952524,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/uabwsydlkghaop8syt9v",
//     },
//     {
//       Timestamp: "2024/03/03 8:34:09 pm GMT+5:30",
//       Username: "valakalpesh878@gmail.com",
//       Name: "Kalpesh vala",
//       "Position/ Role in Triveni": "Creative team membar",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 210280113013,
//       "Phone Number": 9428618420,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/achx3x7vzegtkl3cn7gu",
//     },
//     {
//       Timestamp: "2024/03/03 9:07:08 pm GMT+5:30",
//       Username: "thakkarrachit91@gmail.com",
//       Name: "Rachit Thakkar",
//       "Position/ Role in Triveni": "Creative team",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 220283113017,
//       "Phone Number": 7359335159,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ddjkhujowv4nysksbgga",
//     },
//     {
//       Timestamp: "2024/03/03 9:31:21 pm GMT+5:30",
//       Username: "vatsalp3112@gmail.com",
//       Name: "Vatsal patel",
//       "Position/ Role in Triveni": "creativity team",
//       Department: "Environment",
//       Semester: 6,
//       "Enrollment no": 220283113013,
//       "Phone Number": 9913189074,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/zbayoucf9vstenktnxnu",
//     },
//     {
//       Timestamp: "2024/03/04 12:10:12 am GMT+5:30",
//       Username: "mfafolawala@gmail.com",
//       Name: "Mohit Fafolawala",
//       "Position/ Role in Triveni": "Team Member",
//       Department: "Instrumentation and Control",
//       Semester: 2,
//       "Enrollment no": 230280117044,
//       "Phone Number": 9512942439,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/bsvrxf5mpenioeubvzes",
//     },

//     {
//       Timestamp: "2024/03/04 1:15:57 pm GMT+5:30",
//       Username: "rutva2574@gmail.com",
//       Name: "Rutva Trivedi",
//       "Position/ Role in Triveni": "Marketing team",
//       Department: "Environment",
//       Semester: 4,
//       "Enrollment no": 220280113053,
//       "Phone Number": 8758533104,
//       Photo:
//         "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ybpvgihrxk2foc9rio67",
//     },
//   ],
// };

export const teamData = [
  {
    Timestamp: "3/11/2024 10:10:34",
    firstname: "Satyam",
    lastname: "Sinha ",
    number: 9065284740,
    department: "EC ",
    Semester: 8,
    linkedin: "https://www.linkedin.com/in/satyam-sinha-2296631aa",
    email: "ssinhanwd2019@gmail.com",
    team: "Founders",
    position: "Co-Founder & Advisor",
    imageurl:
      "https://res.cloudinary.com/dxr9qcs8l/image/upload/v1682013812/Prakalpa-Main/Team/Satyam_Sinha_-_Satyam_Sinha_sk7ge0.webp",
  },
  {
    Timestamp: "3/11/2024 10:10:34",
    firstname: "Khushvi",
    lastname: "Purohit",
    number: 9327617291,
    department: "EC ",
    Semester: 8,
    linkedin: "https://www.linkedin.com/in/khushvi-purohit-7117b220b/",
    email: "khushvipurohit59@gmail.com",
    team: "Founders",
    position: "Co-Founder & Advisor",
    imageurl:
      "https://www.lakshyafestldce.in/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdsuwjggl0%2Fimage%2Fupload%2Fv1679832843%2Fa2mi2ltgnnqckiuvffdd.jpg&w=256&q=75",
  },
  {
    Timestamp: "3/11/2024 10:10:34",
    firstname: "Nagesh",
    lastname: "Parmar ",
    number: 7600922879,
    department: "Civil ",
    Semester: 8,
    linkedin: "https://www.linkedin.com/in/nagesh-abhilash-parmar-9b762b147",
    email: "naparmar24@gmail.com",
    team: "Founders",
    position: "Co-Founder & Advisor",
    imageurl:
      "https://res.cloudinary.com/dxr9qcs8l/image/upload/v1682021607/Prakalpa-Main/Team/IMG-20230420-WA0045_-_Nagesh_Abhilash_Parmar_tuk9mc.jpg",
  },
  {
    Timestamp: "3/11/2024 10:10:34",
    firstname: "Ankush",
    lastname: "Zinzala ",
    number: 9714248176,
    department: "Automobile ",
    Semester: 2,
    linkedin: null,
    email: "ankushzinzala@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:10:38",
    firstname: "Vanshika ",
    lastname: "Modi",
    number: 9408477747,
    department: "Textile ",
    Semester: 6,
    linkedin: null,
    email: "Vanshikamodi73@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/cvvoyvp7rhm6xtdlrwmo",
  },
  {
    Timestamp: "3/11/2024 10:10:56",
    firstname: "Hardi",
    lastname: "Priyadarshi ",
    number: 9687242895,
    department: "Environment ",
    Semester: 2,
    linkedin: null,
    email: "hardipriyadarshi@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/vk88q8njuudnleg7yfhg",
  },
  {
    Timestamp: "3/11/2024 10:11:01",
    firstname: "Shreya ",
    lastname: "Mishra",
    number: 8320725508,
    department: "Environment ",
    Semester: 2,
    linkedin: null,
    email: "shreyamishra070905@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:11:13",
    firstname: "Tanushka",
    lastname: "Goswami ",
    number: 9316952524,
    department: "Textile Technology ",
    Semester: 6,
    linkedin: null,
    email: "tanushkagoswami4@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:12:16",
    firstname: "Arvi",
    lastname: "Gondaliya ",
    number: 6352703745,
    department: "Instrumation and control",
    Semester: 2,
    linkedin: null,
    email: "gondaliyaaarvi123@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:12:33",
    firstname: "Vidhan",
    lastname: "Parmar ",
    number: 8401441999,
    department: "Civil ",
    Semester: 6,
    linkedin: null,
    email: "vidhanparmar089@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/cux2zupizzxluucmviyg",
  },
  {
    Timestamp: "3/11/2024 10:12:35",
    firstname: "Ruchi",
    lastname: "Gandhi ",
    number: 9429867363,
    department: "Environment ",
    Semester: 2,
    linkedin: null,
    email: "ruchigandhi1185@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ubjwm2o8qgtck9x2m8rd",
  },
  {
    Timestamp: "3/11/2024 10:12:59",
    firstname: "Smit dikship",
    lastname: "Patel",
    number: 7874164507,
    department: "Instrumentation and control ",
    Semester: 2,
    linkedin: null,
    email: "smitpatel5434@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/jol9zeb3aqdvsnnqcde7",
  },
  {
    Timestamp: "3/11/2024 10:13:17",
    firstname: "Kavya ",
    lastname: "Patel ",
    number: 9265374989,
    department: "IC",
    Semester: 2,
    linkedin: null,
    email: "kavyapatel3805@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/lotezmf65ih9lrdavz6j",
  },
  {
    Timestamp: "3/11/2024 10:13:33",
    firstname: "Sambhav",
    lastname: "Shah",
    number: 7359362681,
    department: "Instrumentation and Control ",
    Semester: 2,
    linkedin: null,
    email: "07sambhav@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ohg4wymoa1vmvcahvxti",
  },
  {
    Timestamp: "3/11/2024 10:14:02",
    firstname: "Mohit ",
    lastname: "Fafolawala ",
    number: 9512942439,
    department: "Instrumentation and Control Engineering ",
    Semester: 2,
    linkedin: "-",
    email: "mfafolawala@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/bsvrxf5mpenioeubvzes",
  },
  {
    Timestamp: "3/11/2024 10:14:22",
    firstname: "Krish",
    lastname: "Suthar",
    number: 9313843173,
    department: "Instrumentation & Control ",
    Semester: 2,
    linkedin: null,
    email: "sutharkrish93@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:15:11",
    firstname: "Dhyan",
    lastname: "Patel",
    number: 9023184128,
    department: "Instrumentation and Control ",
    Semester: 2,
    linkedin:
      "https://www.linkedin.com/in/dhyan-patel-746796289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "dhyan0711@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/qedlx6h8ed1fwlt5hs2y",
  },
  {
    Timestamp: "3/11/2024 10:15:55",
    firstname: "Isha",
    lastname: "Yadav",
    number: 6355578848,
    department: "Textile ",
    Semester: 6,
    linkedin: null,
    email: "ishay5439@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/s6bmtff43guckuqkwdar",
  },
  {
    Timestamp: "3/11/2024 10:16:49",
    firstname: "Dhruvil",
    lastname: "Moradiya",
    number: 7990740133,
    department: "EC",
    Semester: 4,
    linkedin: "https://www.linkedin.com/in/mdhruvil",
    email: "dhruvil1808@gmail.com",
    team: "Web Development",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ie1zs7e3rvp3s7blbise",
  },
  {
    Timestamp: "3/11/2024 10:18:17",
    firstname: "Hitika ",
    lastname: "Padhiyar ",
    number: 7041812298,
    department: "Mechanical ",
    Semester: 6,
    linkedin:
      "https://www.linkedin.com/in/hitika-padhiyar-24726a290?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "hppadhiyar14@gmail.com",
    team: "Events & Management",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/eiclmf9mqlzg3xihjdji",
  },
  {
    Timestamp: "3/11/2024 10:18:37",
    firstname: "Vishvam",
    lastname: "Moliya",
    number: 9429559419,
    department: "AIML",
    Semester: 4,
    linkedin: "https://www.linkedin.com/in/vishvam-moliya",
    email: "vishvammoliya@gmail.com",
    team: "Web Development",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/dtt7p3n7iylbfgzhrwwq",
  },
  {
    Timestamp: "3/11/2024 10:23:35",
    firstname: "Umang ",
    lastname: "Kansagra ",
    number: 7048642441,
    department: "Ic ",
    Semester: 2,
    linkedin: null,
    email: "umangkansagra91@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:25:13",
    firstname: "Pratham",
    lastname: "Panchal",
    number: 8487820364,
    department: "Ic",
    Semester: 2,
    linkedin: null,
    email: "Panchalpratham1008@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ybukcwdxv9x9ve15zyjk",
  },
  {
    Timestamp: "3/11/2024 10:28:39",
    firstname: "Shilpa ",
    lastname: "Yadav ",
    number: 7600218226,
    department: "Environment ",
    Semester: 6,
    linkedin:
      " https://linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=shilpa-yadav-6225232b8",
    email: "shilpakaninwal@gmail.com ",
    team: "Creative Team",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/p2u7ynyijcfmnm7pbe8e",
  },
  {
    Timestamp: "3/11/2024 10:29:13",
    firstname: "bnhadiya53@gmail.com",
    lastname: "bhargav ahir",
    number: 6359768714,
    department: "Rubber technology",
    Semester: 6,
    linkedin: null,
    email: "bnhadiya53@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ifi7fgvbgiq3nrp45i91",
  },
  {
    Timestamp: "3/11/2024 10:33:30",
    firstname: "Arshil",
    lastname: "Hapani",
    number: 7778887156,
    department: "AI/ML",
    Semester: 4,
    linkedin: "https://www.linkedin.com/in/arshil-hapani-19b52a24a",
    email: "arshilhapani998@gmail.com",
    team: "Web Development",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/rbuoshr0evbhmfl7h2ya",
  },
  {
    Timestamp: "3/11/2024 10:34:22",
    firstname: "Kena",
    lastname: "Patel",
    number: 9978886155,
    department: "Ic",
    Semester: 2,
    linkedin: null,
    email: "patelkena74@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/ddwraiu63dv5cwkxvuby",
  },
  {
    Timestamp: "3/11/2024 10:36:16",
    firstname: "Vaidehi ",
    lastname: "ChetanKumar ",
    number: 9313391455,
    department: "Environmental ",
    Semester: 2,
    linkedin: null,
    email: "vaidehicpatel31@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/lqy5qvcygnyq7atmtnyl",
  },
  {
    Timestamp: "3/11/2024 10:51:34",
    firstname: "Mitali",
    lastname: "Agrawal",
    number: 8511384766,
    department: "Environment ",
    Semester: 6,
    linkedin: "-",
    email: "agrawalmitali373@gmail.com",
    team: "Events & Management",
    position: "Convener",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 10:54:28",
    firstname: "Het",
    lastname: "Solanki",
    number: 8849698524,
    department: "Computer",
    Semester: 4,
    linkedin: "https://www.linkedin.com/in/het-solanki-119476216",
    email: "het.solanki109@gmail.com",
    team: "Web Development",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 12:32:34",
    firstname: "Alpa ",
    lastname: "Rathod",
    number: 7069198582,
    department: "Environment ",
    Semester: 6,
    linkedin: null,
    email: "rathodalpa585@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/jfbd1vai06u4hyy7thm2",
  },
  {
    Timestamp: "3/11/2024 12:33:08",
    firstname: "Karan ",
    lastname: "Rathod ",
    number: 6356497758,
    department: "Mechanical ",
    Semester: 2,
    linkedin: null,
    email: "karanpalarathod@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 12:34:13",
    firstname: "Yasmin",
    lastname: "Sanghar",
    number: 6351368735,
    department: "Ic",
    Semester: 2,
    linkedin: null,
    email: "Yasusanghar@786",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 12:34:34",
    firstname: "SAHIL ",
    lastname: "SHYORA ",
    number: 9099426824,
    department: "Environment ",
    Semester: 6,
    linkedin: null,
    email: "mrshyora384@gmail.com",
    team: "Creative Team",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/p64spffibl62z1cokxpc",
  },
  {
    Timestamp: "3/11/2024 12:58:00",
    firstname: "Ahaan ",
    lastname: "Thakore",
    number: 8141265766,
    department: "Environment ",
    Semester: 4,
    linkedin:
      "https://www.linkedin.com/in/ahaan-thakore-32588b270?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "ahaanthakore@gmail.com",
    team: "Campaning & Opereation",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/umqis45hp6x9n7s2eehh",
  },
  {
    Timestamp: "3/11/2024 13:17:05",
    firstname: "Krunal",
    lastname: "Waghela",
    number: 7383316379,
    department: "Automobile ",
    Semester: 6,
    linkedin:
      "https://www.linkedin.com/in/krunal-waghela-70203a248?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "krunalswaghela@gmail.com",
    team: "Events & Management",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/mjfi9v2hoocqkvrpvaqj",
  },
  {
    Timestamp: "3/11/2024 13:24:50",
    firstname: "Hitisha",
    lastname: "Kavar",
    number: 9512914232,
    department: "Environmental",
    Semester: 6,
    linkedin: null,
    email: "hitishakavar1511@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/blf9tqaiwpcprut7jeia",
  },
  {
    Timestamp: "3/11/2024 13:38:46",
    firstname: "Prajapati",
    lastname: "Mahi",
    number: 9313387959,
    department: "Environmental",
    Semester: 6,
    linkedin: null,
    email: "mahip5501@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/hr1qx1icz57phwfvjc5i",
  },
  {
    Timestamp: "3/11/2024 13:54:24",
    firstname: "Yash",
    lastname: "Hirani",
    number: 9898535081,
    department: "EC",
    Semester: 6,
    linkedin: null,
    email: "yashhirani26@gmail.com",
    team: "Sponsorship & Marketing",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/bzkmddhdfrne4a2s7mjh",
  },
  {
    Timestamp: "3/11/2024 13:58:01",
    firstname: "Rutvi",
    lastname: "Moliya",
    number: 9316370146,
    department: "Environment ",
    Semester: 4,
    linkedin: null,
    email: "rutvi17patel@gmail.com",
    team: "Sponsorship & Marketing",
    position: "Team Head",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/oddnega81yngc1htbdpe",
  },
  {
    Timestamp: "3/11/2024 16:07:29",
    firstname: "Pooja",
    lastname: "Roshiya",
    number: 6356720073,
    department: "I &C",
    Semester: 2,
    linkedin: null,
    email: "poojaroshiya11@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/u8yhnahupbmlrlsg6wdu",
  },
  {
    Timestamp: "3/11/2024 21:15:56",
    firstname: "Dhruv",
    lastname: "Prajapati ",
    number: 7043341434,
    department: "Environment ",
    Semester: 6,
    linkedin: null,
    email: "dhruvenv2021@gmail.com",
    team: "Events & Management",
    position: "Team Head",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:28:48",
    firstname: "Namrata ",
    lastname: "Rathod ",
    number: 9510819632,
    department: "Robotics and Automation ",
    Semester: 4,
    linkedin:
      "https://www.linkedin.com/in/namrata-rathod-06b0112a4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "namratarathod80@gmail.com",
    team: "Events & Management",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:28:50",
    firstname: "Darshit ",
    lastname: "Ghevariya ",
    number: 9924997264,
    department: "Textile technology ",
    Semester: 6,
    linkedin: null,
    email: "azlsjxn173@gmail.com",
    team: "Events & Management",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:46:24",
    firstname: "Roshni",
    lastname: "Patara",
    number: 7285076097,
    department: "TEXTILE ",
    Semester: 6,
    linkedin: null,
    email: "roshnipatara767@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/vnxw1p7umbrq4f8r6t8x",
  },
  {
    Timestamp: "3/11/2024 21:47:28",
    firstname: "Uttam",
    lastname: "Prajapati ",
    number: 9773056664,
    department: "Textile ",
    Semester: 6,
    linkedin: null,
    email: "prajapatiuttam1413@gmail.com",
    team: "Events & Management",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:51:24",
    firstname: "Khushi ",
    lastname: "Singh ",
    number: 9586250738,
    department: "Environmental engineering ",
    Semester: 6,
    linkedin: null,
    email: "khushi7321singh@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl:
      "https://res.cloudinary.com/dk6oyez3u/image/upload/f_auto,q_auto/eknhoybz2ub44mkboz9v",
  },
  {
    Timestamp: "3/11/2024 21:52:06",
    firstname: "Devkumar",
    lastname: "Parmar",
    number: 9428866698,
    department: "Electrical",
    Semester: 2,
    linkedin: null,
    email: "parmardev2006@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:57:50",
    firstname: "Trushil",
    lastname: "Shyora",
    number: 9824994014,
    department: "Environment",
    Semester: 6,
    linkedin: null,
    email: "ahirtrushil00@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },

  {
    Timestamp: "3/11/2024 21:58:07",
    firstname: "Vatsal ",
    lastname: "Patel ",
    number: 9913189074,
    department: "Environment ",
    Semester: 6,
    linkedin: null,
    email: "patelvatsal9230@gmail.com ",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 21:59:00",
    firstname: "Divyesh",
    lastname: "Shyora",
    number: 7984679355,
    department: "Environmental",
    Semester: 4,
    linkedin: null,
    email: "shyoradivyesh66769@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
  {
    Timestamp: "3/11/2024 22:01:38",
    firstname: "Anjali",
    lastname: "Mistry",
    number: 9106803914,
    department: "Electrical",
    Semester: 2,
    linkedin: null,
    email: "nayanmistry9106803914@gmail.com",
    team: "Creative Team",
    position: "Team Member",
    imageurl: null,
  },
];
